version: 0.0
os: linux
files:
  # unzip the build artifact in ~/nodejs
  - source: /
    destination: /home/ubuntu/nodejs
    overwrite: true
hooks:
  BeforeInstall: 
    - location : deploy/stop.sh
      timeout: 300
      runas: root
  Install:
    - location: deploy/start_up.sh
      timeout: 300
      runas: root
