version: 0.0
os: linux
files:
  # unzip the build artifact in ~/app
  - source: /
    destination: /home/ubuntu/nodejs
permissions:
  # change permissions from root to ec2-user
  - object: /home/ubuntu/nodejs
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  Install:
    - location: deploy/start.sh
      timeout: 300
      runas: root
